---
- name: Label Rook nodes
  oc_label:
    name: "{{ hostvars[item].l_kubelet_node_name }}"
    kind: node
    state: add
    labels: "{{ rook_ceph_nodeselector | lib_utils_oo_dict_to_list_of_dict }}"
  with_items: "{{ rook_ceph_nodes | default([]) }}"
