---
- name: Label Rook nodes
  oc_label:
    name: "{{ hostvars[item].l_kubelet_node_name }}"
    kind: node
    state: add
    labels: "{{ rook_ceph_nodeselector | lib_utils_oo_dict_to_list_of_dict }}"
  with_items: "{{ rook_ceph_nodes | default([]) }}"

- name: Taint all nodes to have rook ceph agent
  command: >
    {{ openshift_client_binary }} --config=/etc/origin/master/admin.kubeconfig adm taint nodes {{ item }} rook-storage=true:NoSchedule
  with_items: "{{ nodes | default([]) }}"
  failed_when: False