---
- set_fact:
    rook_ceph_wipe: "{{ openshift_storage_rook_wipe | default('false') | bool }}"
    rook_ceph_namespace: "{{ openshift_storage_rook_ceph_namespace | default('rook-ceph') }}"
    rook_ceph_nodes: "{{ groups.rookceph | default([]) }}"
    rook_ceph_system_namespace: "{{ openshift_storage_rook_ceph_system_namespace | default('rook-ceph-system') }}"
    rook_ceph_nodeselector:
      'node-role.kubernetes.io/rook': true