---
- import_tasks: mktemp.yml

- assert:
    that: "rook_ceph_nodes | count >= 3"
    msg: There must be at least three rook ceph nodes specified

- name: Copy Rook Ceph Security
  copy:
    src: "rook-ceph-scc.yml"
    dest: "{{ mktemp.stdout }}/rook-ceph-scc.yml"

- name: Create Rook Ceph Security
  oc_obj:
    kind: "SecurityContextConstraints"
    name: "rook-ceph"
    state: present
    files:
    - "{{ mktemp.stdout }}/rook-ceph-scc.yml"

- import_tasks: label_nodes.yml

- name: Verify target namespace exists
  oc_project:
    state: present
    name: "{{ rook_ceph_system_namespace }}"

- name: Copy Rook Ceph Operator template
  copy:
    src: "rook-ceph-operator-template.yml"
    dest: "{{ mktemp.stdout }}/rook-ceph-operator-template.yml"

- name: Create Rook Ceph template
  oc_obj:
    namespace: "{{ rook_ceph_system_namespace }}"
    kind: template
    name: "rook-ceph"
    state: present
    files:
    - "{{ mktemp.stdout }}/rook-ceph-operator-template.yml"

- name: Deploy Rook Operator
  oc_process:
    namespace: "{{ rook_ceph_system_namespace }}"
    template_name: "rook-ceph"
    create: True

- name: Create Rook Ceph Namespace
  oc_project:
    state: present
    name: "{{ rook_ceph_namespace }}"
    node_selector:
      - node-role.kubernetes.io/rook=True

#setup pod network settings
- name: Make both projects able to talk to each other with multitenant
  command: >
    {{ openshift_client_binary }} --config=/etc/origin/master/admin.kubeconfig adm pod-network join-projects --to {{ rook_ceph_namespace }} {{ rook_ceph_system_namespace }}

- name: Make ceph project global
  command: >
    {{ openshift_client_binary }} --config=/etc/origin/master/admin.kubeconfig adm pod-network make-projects-global {{ rook_ceph_namespace }}


- name: Generate cluster file
  template:
    src: "rook-ceph-cluster.yml.j2"
    dest: "{{ mktemp.stdout }}/rook-ceph-cluster.yml"

- name: Create Rook Ceph Cluster
  oc_obj:
    namespace: "{{ rook_ceph_namespace }}"
    kind: "ServiceAccount"
    name: "rook-ceph-osd"
    state: present
    files:
    - "{{ mktemp.stdout }}/rook-ceph-cluster.yml"

- name: Generate security file
  template:
    src: "rook-ceph-system-privs.yml.j2"
    dest: "{{ mktemp.stdout }}/rook-ceph-system-privs.yml"

- name: Create Rook Ceph Privs
  oc_obj:
    namespace: "{{ rook_ceph_system_namespace }}"
    kind: "RoleBinding"
    name: "rook-ceph-mgr-system"
    state: present
    files:
    - "{{ mktemp.stdout }}/rook-ceph-system-privs.yml"

- name: Copy Rook Ceph storage yml
  copy:
    src: "rook-ceph-storageclass.yml"
    dest: "{{ mktemp.stdout }}/rook-ceph-storageclass.yml"

- name: Create rook ceph storage class
  oc_obj:
    namespace: "{{ rook_ceph_namespace }}"
    kind: StorageClass
    name: rook-ceph-block
    state: present
    files:
    - "{{ mktemp.stdout }}/rook-ceph-storageclass.yml"